### ISSUE TITLE
swaggerのclient周りのところに権限の記述がない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ#660]
```yaml
      security:
        - traqOAuth2:
            - write
```
みたいなの
